version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  worker:
    command: celery worker --loglevel=info
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  client:
    image: raulronald/dummy-celery-client:latest
    command: /bin/sh -c "python other_codebase_client.py && python other_codebase_client.py && tail -f /dev/null"
    depends_on:
      - redis
      - worker
