version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  worker:
    command: celery worker --loglevel=info
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  client:
    image: raulronald/dummy-celery-client:latest
    # command: /bin/sh -c "python other_codebase_client.py && python other_codebase_client.py && tail -f /dev/null"
    command: /bin/sh -c "tail -f /dev/null"
    depends_on:
      - redis
      - worker

  flower:
    image: "mher/flower:2.0.1"
    command: celery --broker=redis://redis:6379/0 flower
    ports:
      - "5555:5555"
    depends_on:
      - redis